config/routes.rb
Rails.application.routes.draw do

  root :to => 'trips#index'

  get 'trips/:trip_id/expenses/add' => 'expenses#add', as: :add_expense
  post 'expenses' => 'expenses#create'

  get 'trips/:trip_id/expenses/history' => 'expenses#history', as: :history_expense
  get 'trips/:trip_id/expenses/chart' => 'expenses#chart', as: :chart

  delete '/expenses/:id' => 'expenses#destroy', as: :delete_expense

  resources :trips
  resources :expense_categories
  resources :destinations

  get '/signup' => 'users#signup', as: :signup_user_path
  post '/signup' => 'users#create'
  get '/users' => 'users#index'

  get    '/login'  => 'sessions#login'
  post   '/login'  => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :destination
  belongs_to :user
  has_many :expenses

  validates :user_id, presence: true

  validates :name, presence: true, uniqueness: true
  validates :budget, numericality: true

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  def total_amount
    expenses.sum { |expense| expense.amount }
  end

  def budget_based_on_destination
    budget * destination.exchange_rate
  end

  def remaining
    budget_based_on_destination - total_amount
  end

  def percentual_remaining
    (remaining * 100) /budget_based_on_destination
  end

  def number_of_days
    (start_date..end_date).count
  end

  def daily_budget
    budget_based_on_destination / number_of_days
  end

  def expenses_by_day
    expenses_by_group = expenses.group_by { |expense| expense.expense_date }

    # Create a new hash which the key is a date and value is a sum of expenses of that date
    total_expense_by_date = {}

    last_7_days.each do |day|
      expenses = expenses_by_group[day] || []
      total_expense_by_date[day] = expenses.sum { |e| e.amount }
    end

    total_expense_by_date
  end

  def expenses_by_category
    # Groups all expenses by category
    expenses_by_group = expenses.group_by {|expense| expense.expense_category.name}

    # Create a new hash which the key is a category and value is a sum of expenses of that category
    total_expense_by_category = {}
    expenses_by_group.each do |key, value|
      total_expense_by_category[key] = value.sum { |e| e.amount }
    end

    total_expense_by_category
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end

  def last_7_days
    Date.today.downto(Date.today - 6).to_a.reverse
  end



end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :check_login!

  def index
    @trips = Trip.where(user: current_user.id)
  end

  def show
    #Find a current user and the trip regarding that user
    @trip = find_trip(params)
    return render_not_found if @trip == nil

    expenses_by_the_last_7_days = @trip.expenses_by_day

    @data = {
      labels: expenses_by_the_last_7_days.keys.map { |date| date.strftime("%a, %d %b") },
      datasets: [
        {
            label: "My Trip",
            backgroundColor: "rgba(250,128,114,0.2)",
            borderColor: "rgba(250,128,114,1)",
            data: expenses_by_the_last_7_days.values
        }
      ]
    }

  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
    @trip = find_trip(params)
    return render_not_found if @trip == nil
  end

  # POST /trips
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /trips/1
  def update
    @trip = find_trip(params)
    return render_not_found if @trip == nil

    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /trips/1
  def destroy
    @trip = find_trip(params)
    return render_not_found if @trip == nil

    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
    end
  end

  private

    def find_trip(params)
      Trip.find_by(user: current_user.id, id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :start_date, :end_date, :budget, :destination_id).merge({ user_id: current_user.id })
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= render 'shared/error_messages', locals: { errors: @trip.errors } %>

<div class="flex-grid">
  <%= form_with(model: trip, local: true) do |form| %>
    <div>
      <div class="col" id="login-form">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: "Summer Holiday", autofocus: true%>
      </div>
      <div class="col" id="login-form">
        <%= form.label :start_date %>
        <%= form.date_field :start_date, min: Date.today, value: Date.today %>
      </div>
      <div class="col" id="login-form">
        <%= form.label :end_date %>
        <%= form.date_field :end_date, value: Date.tomorrow %>
      </div>
      <div class="col" id="login-form">
        <%= form.label :budget %>
        <%= form.number_field :budget, step: :any, precision: 2, pattern: "\d*", placeholder: "AUD $   1000.00" %>
      </div>
      <div class="col" id="login-form">
        <%= form.label :destination %>
        <%= form.select :destination_id, Destination.all.map { |d| [d.name, d.id] }, include_blank: 'Please choose' %>
      </div>
    </div>
    <div class="col form-submit">
      <div class="form-submit-placeholder"></div>
      <div class="form-submit-action"><%= form.submit %></div>
    </div>
  <% end %>
</div>

app/views/trips/edit.html.erb
<div class="flex-grid-links">
  <div class="col navigation">
    <%= link_to 'Summary', @trip %>
  </div>
</div>
<div class="flex-grid">
  <div class="col">
    <h1>Editing Trip</h1>
  </div>
</div>

<%= render 'shared/error_messages', locals: { errors: @trip.errors } %>

<div class="flex-grid">
  <%= form_with(model: @trip, local: true) do |form| %>
    <div class="col" id="login-form">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: "Summer Holiday", autofocus: true%>
    </div>
    <div class="col" id="login-form">
      <%= form.label :start_date %>
      <%= form.date_field :start_date, min: @trip.start_date %>
    </div>
    <div class="col" id="login-form">
      <%= form.label :end_date %>
      <%= form.date_field :end_date %>
    </div>
    <div class="col" id="login-form">
      <%= form.label :budget %>
      <%= form.number_field :budget, placeholder: "AUD $   1000.00" %>
    </div>
    <div class="col" id="login-form">
      <%= form.label :destination %>
      <%= form.select :destination_id, Destination.all.map { |d| [d.name, d.id] }, include_blank: 'Please choose' %>
    </div>
    <div class="col form-submit">
      <div class="form-submit-placeholder"></div>
      <div class="form-submit-action"><%= form.submit %></div>
    </div>
  <% end %>
</div>

app/views/trips/index.html.erb
<% if admin? == false  %>
  <div class="flex-grid">
    <div class="col">
      <h1>My Trips</h1>
    </div>
  </div>
  <% if notice != nil %>
    <div class="flex-grid">
      <div class="col">
        <i class="fas fa-check-circle" id="notice"> <%= notice %></i>
      </div>
    </div>
  <% end %>
  <div>
    <div>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Destination</th>
            <%# <th colspan="3"></th> %>
          </tr>
        </thead>
        <tbody>
          <% @trips.each do |trip| %>
            <tr>
              <td><%= link_to '-', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to trip do %>
                  <%= trip.name %></td>
              <% end %>
              <td><%= trip.destination.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="flex-grid-links actions">
    <div class="col actions" id="single-link">
      <%= link_to 'New Trip', new_trip_path %>
    </div>
  </div>
<% end  %>

app/views/trips/new.html.erb
  <div class="flex-grid-links">
   <div class="col navigation">
    <%= link_to 'My Trips', trips_path %>
  </div>
</div>

<div class="flex-grid">
  <div class="col">
    <h1>New Trip</h1>
  </div>
</div>

<%= render 'form', trip: @trip %>

app/views/trips/show.html.erb
<div class="flex-grid-links">
  <div class="col navigation">
    <%= link_to 'My Trips', trips_path %>
  </div>
  <div class="col navigation">
    <%= link_to 'Edit', edit_trip_path(@trip) %>
  </div>
</div>

<div class="flex-grid">
  <div class="col">
    <h1>Summary</h1>
  </div>
</div>

<% if notice != nil %>
  <div class="flex-grid">
    <div class="col">
      <i class="fas fa-check-circle" id="notice"> <%= notice %></i>
    </div>
  </div>
<% end %>

<div class="flex-grid">
  <div class="col">
    <div class="name-trip">
      <p><%= @trip.name %></p>
      <p><i class="fas fa-globe-asia"></i> <%= @trip.destination.name %></p>
    </div>
    <div class="date-trip">
      <p>
        <i class="fas fa-plane-departure"> </i>
        <%= @trip.start_date.strftime("%d / %m / %y") %>
      </p>
      <p>
        <i class="fas fa-plane-arrival"></i>
        <%= @trip.end_date.strftime("%d / %m / %y") %>
      </p>
    </div>
  </div>
</div>

<div class="flex-grid">
  <div class="col bar-chart">
        <%= bar_chart @data, { responsive: true } %>
  </div>
</div>


<div class="flex-grid">
  <div class="col all-budget">

    <div class="budget-trip">
      <p>
        <i class="fas fa-wallet"></i>
        <span>Budget Trip:</span>
        <%= "#{@trip.destination.symbol} #{number_with_precision(@trip.budget_based_on_destination, precision: 2)}" %>
      </p>
      <p>
        <span>Daily Budget:</span>
        <%= "#{@trip.destination.symbol} #{number_with_precision(@trip.daily_budget , precision: 2)}" %> (<%= @trip.number_of_days %>)
      </p>
      </br>
      <p>
        <i class="fas fa-coins"></i>
        <span>Remaining:</span>
        <%= "#{@trip.destination.symbol} #{number_with_precision(@trip.remaining , precision: 2)}" %>
      </p>
      <p>
        <i class="fas fa-percentage"></i>
        <%= "#{@trip.destination.symbol} #{number_with_precision(@trip.percentual_remaining , precision: 2)}" %>
      </p>
    </div>

  <div class="expense-trip">
    <p>
      <i class="fas fa-file-invoice-dollar"></i>
      <span>EXPENSES:</span>
    </p>
    <p>
      <%= "#{@trip.destination.symbol} #{number_with_precision(@trip.total_amount, precision: 2)}" %>
    </p>
  </div>

  </div>
</div>

<div class="flex-grid-links actions">
  <div class="col actions">
      <%= link_to chart_path(@trip.id) do %>
        <i class="fas fa-chart-pie fa-lg"></i>
      <% end %>
  </div>
  <div class="col actions" id="expense">
    <%= link_to 'Add Expense', add_expense_path(@trip.id) %>
  </div>
  <div class="col actions">
    <%= link_to "/trips/#{@trip.id}/expenses/history" do %>
      <i class="fas fa-receipt fa-lg"></i>
    <% end %>
  </div>
</div>