config/routes.rb
Rails.application.routes.draw do

  root :to => 'trips#index'

  get 'trips/:trip_id/expenses/add' => 'expenses#add', as: :add_expense
  post 'expenses' => 'expenses#create'

  get 'trips/:trip_id/expenses/history' => 'expenses#history', as: :history_expense
  get 'trips/:trip_id/expenses/chart' => 'expenses#chart', as: :chart

  delete '/expenses/:id' => 'expenses#destroy', as: :delete_expense

  resources :trips
  resources :expense_categories
  resources :destinations

  get '/signup' => 'users#signup', as: :signup_user_path
  post '/signup' => 'users#create'
  get '/users' => 'users#index'

  get    '/login'  => 'sessions#login'
  post   '/login'  => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
end

app/controllers/expense_categories_controller.rb
class ExpenseCategoriesController < ApplicationController
  before_action :set_expense_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin!

  # GET /expense_categories
  # GET /expense_categories.json
  def index
    @expense_categories = ExpenseCategory.all
  end

  # GET /expense_categories/1
  # GET /expense_categories/1.json
  def show
  end

  # GET /expense_categories/new
  def new
    @expense_category = ExpenseCategory.new
  end

  # GET /expense_categories/1/edit
  def edit
  end

  # POST /expense_categories
  # POST /expense_categories.json
  def create
    @expense_category = ExpenseCategory.new(expense_category_params)

    respond_to do |format|
      if @expense_category.save
        format.html { redirect_to expense_categories_path, notice: 'Expense category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /expense_categories/1
  # PATCH/PUT /expense_categories/1.json
  def update
    respond_to do |format|
      if @expense_category.update(expense_category_params)
        format.html { redirect_to expense_categories_path, notice: 'Expense category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /expense_categories/1
  # DELETE /expense_categories/1.json
  def destroy
    @expense_category.destroy
    respond_to do |format|
      format.html { redirect_to expense_categories_url, notice: 'Expense category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense_category
      @expense_category = ExpenseCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_category_params
      params.require(:expense_category).permit(:name)
    end
end

app/helpers/expense_categories_helper.rb
module ExpenseCategoriesHelper
end

app/views/expense_categories/_form.html.erb
<%= render 'shared/error_messages', locals: { errors: expense_category.errors } %>

<div class="flex-grid">
  <%= form_with(model: expense_category, local: true) do |form| %>

    <div class="col" id="login-form">
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true, :required => true  %>
    </div>

    <div class="col form-submit">
      <div class="form-submit-placeholder"></div>
      <div class="form-submit-action"><%= form.submit "Create" %></div>
    </div>
  <% end %>
</div>

app/views/expense_categories/edit.html.erb
<div class="flex-grid-links">
  <div class="col navigation">
    <%= link_to 'Back', expense_categories_path %>
 </div>
</div>

<div class="flex-grid">
  <div class="col">
    <h1>Editing Expense Category</h1>
 </div>
</div>


<%= render 'form', expense_category: @expense_category %>

app/views/expense_categories/index.html.erb
<div class="flex-grid">
  <div class="col">
    <h1>Expense Categories</h1>
  </div>
</div>

<% if notice != nil %>
  <div class="flex-grid">
    <div class="col">
      <i class="fas fa-check-circle" id="notice"> <%= notice %></i>
    </div>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expense_categories.sort_by{ |e| e.name }.each do |expense_category| %>
      <tr>
      <td><%= link_to '-', expense_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= expense_category.name %></td>
        <td><%= link_to 'Edit', edit_expense_category_path(expense_category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="flex-grid-links actions">
  <div class="col actions" id="single-link">
    <%= link_to 'New Expense Category', new_expense_category_path %>
  </div>
</div>

app/views/expense_categories/new.html.erb
<div class="flex-grid-links">
  <div class="col navigation">
    <%= link_to 'Categories', expense_categories_path %>
  </div>
</div>

<div class="flex-grid">
  <div class="col">
    <h1>New Expense Category</h1>
  </div>
</div>

<%= render 'form', expense_category: @expense_category %>