config/routes.rb
Rails.application.routes.draw do

  root :to => 'trips#index'

  get 'trips/:trip_id/expenses/add' => 'expenses#add', as: :add_expense
  post 'expenses' => 'expenses#create'

  get 'trips/:trip_id/expenses/history' => 'expenses#history', as: :history_expense
  get 'trips/:trip_id/expenses/chart' => 'expenses#chart', as: :chart

  delete '/expenses/:id' => 'expenses#destroy', as: :delete_expense

  resources :trips
  resources :expense_categories
  resources :destinations

  get '/signup' => 'users#signup', as: :signup_user_path
  post '/signup' => 'users#create'
  get '/users' => 'users#index'

  get    '/login'  => 'sessions#login'
  post   '/login'  => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_error_messages.html.erb
<div class="flex-grid">
  <div class="col">
    <% if locals[:errors].any? %>
      <div id="error_explanation">
        <h2><i class="fas fa-exclamation-circle"></i> <%= pluralize(locals[:errors].count, "error") %> prohibited from being submitted:</h2>
        <ul>
          <% locals[:errors].full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="flex-grid-header">

     <div class="col" id="home">

        <%= link_to root_path do %>
           <i class="fas fa-money-check-alt fa-lg"></i>
        <% end %>

        <p id="brand-name"><%= link_to "Trip Wallet", root_path %></p>
    </div>

     <div class="col" id="login">

          <% if logged_in? %>
            <div class="current-user">
              <p id="gravata"><%= gravatar_for current_user %> </p>
              <p id="gravata-name"><%= current_user.name %></p>
            </div>

            <div class="link-login">
              <p id="logout"><%= link_to "Log out", logout_path, method: :delete %></p>
            </div>

          <% else %>
           <div class="link-login">
            <p><%= link_to "Log in", login_path %></p>
             </div>
          <% end %>

          <% if admin? %>
            <div class="admin-login">
              <p><%= link_to "Users", '/users' %></p>
              <p><%= link_to 'Destinations', destinations_path %></p>
              <p><%= link_to 'Categories', expense_categories_path %></p>
            </div>
          <% end %>

    </div>

</header>