config/routes.rb
Rails.application.routes.draw do

  root :to => 'trips#index'

  get 'trips/:trip_id/expenses/add' => 'expenses#add', as: :add_expense
  post 'expenses' => 'expenses#create'

  get 'trips/:trip_id/expenses/history' => 'expenses#history', as: :history_expense
  get 'trips/:trip_id/expenses/chart' => 'expenses#chart', as: :chart

  delete '/expenses/:id' => 'expenses#destroy', as: :delete_expense

  resources :trips
  resources :expense_categories
  resources :destinations

  get '/signup' => 'users#signup', as: :signup_user_path
  post '/signup' => 'users#create'
  get '/users' => 'users#index'

  get    '/login'  => 'sessions#login'
  post   '/login'  => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]
  before_action :check_admin!

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to destinations_path, notice: 'Destination was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to destinations_path, notice: 'Destination was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :currency, :symbol, :exchange_rate)
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= render 'shared/error_messages', locals: { errors: destination.errors } %>

<div class="flex-grid">
  <%= form_with(model: destination, local: true) do |form| %>

    <div class="col" id="login-form">
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true, :required => true  %>
    </div>

    <div class="col" id="login-form">
      <%= form.label :currency %>
      <%= form.text_field :currency %>
    </div>

    <div class="col" id="login-form">
      <%= form.label :symbol %>
      <%= form.text_field :symbol  %>
    </div>

    <div class="col" id="login-form">
      <%= form.label :exchange_rate, "Rate" %>
      <%= form.text_field :exchange_rate, :required => true  %>
    </div>

    <div class="col form-submit">
      <div class="form-submit-placeholder"></div>
      <div class="form-submit-action"><%= form.submit %></div>
    </div>
  <% end %>
</div>

app/views/destinations/edit.html.erb
<div class="flex-grid-links">
  <div class="col navigation">
    <%= link_to 'Back', destinations_path %>
  </div>
</div>

<div class="flex-grid">
  <div class="col">
    <h1>Editing Destination</h1>
  </div>
</div>


<%= render 'form', destination: @destination %>

app/views/destinations/index.html.erb
<div class="flex-grid">
  <div class="col">
    <h1>Destinations</h1>
  </div>
</div>

<% if notice != nil %>
  <div class="flex-grid">
    <div class="col">
      <i class="fas fa-check-circle" id="notice"> <%= notice %></i>
    </div>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Currency</th>
      <th>Symbol</th>
      <th>Exchange rate</th>
    </tr>
  </thead>
  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= link_to '-', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= destination.name %></td>
        <td><%= destination.currency %></td>
        <td><div class="exchange-rate"><%= destination.symbol %></div></td>
        <td><div class="exchange-rate"><%= destination.exchange_rate %></div></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="flex-grid-links actions">
  <div class="col actions" id="single-link">
    <%= link_to 'New Destination', new_destination_path %>
  </div>
</div>

app/views/destinations/new.html.erb
<div class="flex-grid-links">
  <div class="col navigation">
    <%= link_to 'Back', destinations_path %>
 </div>
</div>

<div class="flex-grid">
  <div class="col">
    <h1>New Destination</h1>
 </div>
</div>


<%= render 'form', destination: @destination %>